#include "../opcode.h"

#define NOT_IMPLEMENTED TBL_NONE, MODE_INVALID , FLG_NOT_IMPLEMENTED,FLG_NOT_IMPLEMENTED,FLG_NOT_IMPLEMENTED

struct opcode_one_byte one_byte_opcodes[] = {
    {TBL_ONE_BYTE, MODE_8, FLG_RM, FLG_REG, OPC_ADD}, /* 0x00 */
    {TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_REG,  OPC_ADD}, /* 0x01 */
    {TBL_ONE_BYTE, MODE_8, FLG_REG, FLG_RM,  OPC_ADD}, /* 0x02 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_RM,  OPC_ADD}, /* 0x03 */
	{TBL_ONE_BYTE, MODE_8, FLG_REG_CONST | AL, FLG_IMM,  OPC_ADD}, /* 0x04 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_IMM,  OPC_ADD}, /* 0x05 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_SEG_CONST | ES, FLG_NONE,  OPC_PUSH}, /* 0x06 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_SEG_CONST | ES, FLG_NONE,  OPC_POP}, /* 0x07 */
	{TBL_ONE_BYTE, MODE_8, FLG_RM, FLG_REG,  OPC_OR}, /* 0x08 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_REG,  OPC_OR}, /* 0x09 */
	{TBL_ONE_BYTE, MODE_8, FLG_REG, FLG_RM,  OPC_OR}, /* 0x0A */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_RM, OPC_OR}, /* 0x0B */
	{TBL_ONE_BYTE, MODE_8, FLG_REG_CONST | AL, FLG_IMM, OPC_OR}, /* 0x0C */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_IMM, OPC_OR}, /* 0x0D */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_SEG_CONST | CS, FLG_NONE, OPC_PUSH}, /* 0x0E */

	{TBL_NONE, MODE_INVALID, FLG_INVALID, FLG_INVALID, FLG_INVALID}, /* 0x0F */

	{TBL_ONE_BYTE, MODE_8,  FLG_RM, FLG_REG, OPC_ADC}, /* 0x10 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_REG, OPC_ADC }, /* 0x11 */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG, FLG_RM, OPC_ADC }, /* 0x12 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_RM, OPC_ADC }, /* 0x13 */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG_CONST | AL, FLG_IMM,  OPC_ADC }, /* 0x14 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_IMM,  OPC_ADC }, /* 0x15 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_SEG_CONST | SS, FLG_NONE, OPC_PUSH }, /* 0x16 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_SEG_CONST | SS, FLG_NONE, OPC_POP }, /* 0x17 */

	{TBL_ONE_BYTE, MODE_8,  FLG_RM, FLG_REG, OPC_SBB }, /* 0x18 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_REG, OPC_SBB }, /* 0x19 */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG, FLG_RM,  OPC_SBB }, /* 0x1A */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_RM,  OPC_SBB }, /* 0x1B */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG_CONST | AL, FLG_IMM,  OPC_SBB }, /* 0x1C */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_IMM,  OPC_SBB }, /* 0x1D */

	{TBL_ONE_BYTE, MODE_DEFAULT,FLG_SEG_CONST | DS, FLG_NONE,  OPC_PUSH }, /* 0x1E */
	{TBL_ONE_BYTE, MODE_DEFAULT,FLG_SEG_CONST | DS, FLG_NONE,  OPC_POP }, /* 0x1F */

	{TBL_ONE_BYTE, MODE_8,  FLG_RM, FLG_REG,OPC_AND }, /* 0x20 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_REG,OPC_AND }, /* 0x21 */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG, FLG_RM, OPC_AND }, /* 0x22 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_RM, OPC_AND }, /* 0x23 */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG_CONST | AL, FLG_IMM8, OPC_AND }, /* 0x24 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_IMM, OPC_AND }, /* 0x25 */

	{TBL_NONE, MODE_INVALID, FLG_PREFIX, FLG_NONE, FLG_NONE}, /* 0x26 */

	{TBL_ONE_BYTE, MODE_8,  FLG_REG_CONST | AL, FLG_NONE, OPC_DAA }, /* 0x27 */

	{TBL_ONE_BYTE, MODE_8,  FLG_RM, FLG_REG,  OPC_SUB }, /* 0x28 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_REG, OPC_SUB }, /* 0x29 */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG, FLG_RM, OPC_SUB }, /* 0x2A */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_RM, OPC_SUB }, /* 0x2B */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG_CONST | AL, FLG_IMM,  OPC_SUB }, /* 0x2C */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_IMM,  OPC_SUB }, /* 0x2D */

	{TBL_ONE_BYTE, MODE_INVALID, FLG_PREFIX, FLG_NONE,  FLG_NONE }, /* 0x2E */

	{TBL_ONE_BYTE, MODE_8,  FLG_REG_CONST | AL, FLG_NONE,  OPC_DAS }, /* 0x2F */

	{TBL_ONE_BYTE, MODE_8,  FLG_RM, FLG_REG,  OPC_XOR }, /* 0x30 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_REG,  OPC_XOR }, /* 0x31 */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG, FLG_RM, OPC_XOR }, /* 0x32 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_RM,  OPC_XOR }, /* 0x33 */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG_CONST | AL, FLG_IMM,  OPC_XOR }, /* 0x34 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_IMM,  OPC_XOR }, /* 0x35 */

	{TBL_ONE_BYTE, MODE_INVALID, FLG_PREFIX, FLG_NONE, FLG_NONE }, /* 0x36 */

	{TBL_ONE_BYTE, MODE_8,  FLG_REG_CONST | AL, FLG_REG_CONST | AH,  OPC_AAA }, /* 0x37 */

	{TBL_ONE_BYTE, MODE_8, FLG_RM, FLG_REG, OPC_CMP }, /* 0x38 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_REG,  OPC_CMP }, /* 0x39 */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG, FLG_RM, OPC_CMP }, /* 0x3A */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_RM, OPC_CMP }, /* 0x3B */
	{TBL_ONE_BYTE, MODE_8,  FLG_REG_CONST | AL, FLG_IMM8,  OPC_CMP }, /* 0x3C */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_IMM,  OPC_CMP }, /* 0x3D */

	{TBL_ONE_BYTE, MODE_INVALID, FLG_PREFIX | FLG_NONE, FLG_NONE,  FLG_NONE }, /* 0x3E */

	{TBL_ONE_BYTE, MODE_8,  FLG_REG_CONST | AL, FLG_REG_CONST | AH, OPC_AAA }, /* 0x3F */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_NONE, OPC_INC }, /* 0x40 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ECX, FLG_NONE, OPC_INC }, /* 0x41 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EDX, FLG_NONE, OPC_INC }, /* 0x42 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EBX, FLG_NONE, OPC_INC }, /* 0x43 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ESP, FLG_NONE, OPC_INC }, /* 0x44 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EBP, FLG_NONE, OPC_INC }, /* 0x45 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ESI, FLG_NONE,  OPC_INC }, /* 0x46 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EDI, FLG_NONE,  OPC_INC }, /* 0x47 */

	{TBL_ONE_BYTE, MODE_DEFAULT,FLG_REG_CONST | EAX, FLG_NONE, OPC_DEC }, /* 0x48 */
	{TBL_ONE_BYTE, MODE_DEFAULT,FLG_REG_CONST | ECX, FLG_NONE, OPC_DEC }, /* 0x49 */
	{TBL_ONE_BYTE, MODE_DEFAULT,FLG_REG_CONST | EDX, FLG_NONE,  OPC_DEC }, /* 0x4A */
	{TBL_ONE_BYTE, MODE_DEFAULT,FLG_REG_CONST | EBX, FLG_NONE,  OPC_DEC }, /* 0x4B */
	{TBL_ONE_BYTE, MODE_DEFAULT,FLG_REG_CONST | ESP, FLG_NONE, OPC_DEC }, /* 0x4C */
	{TBL_ONE_BYTE, MODE_DEFAULT,FLG_REG_CONST | EBP, FLG_NONE,  OPC_DEC }, /* 0x4D */
	{TBL_ONE_BYTE, MODE_DEFAULT,FLG_REG_CONST | ESI, FLG_NONE,  OPC_DEC }, /* 0x4E */
	{TBL_ONE_BYTE, MODE_DEFAULT,FLG_REG_CONST | EDI, FLG_NONE,  OPC_DEC }, /* 0x4F */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_NONE, OPC_PUSH }, /* 0x50 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ECX, FLG_NONE, OPC_PUSH }, /* 0x51 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EDX, FLG_NONE, OPC_PUSH }, /* 0x52 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EBX, FLG_NONE, OPC_PUSH }, /* 0x53 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ESP, FLG_NONE, OPC_PUSH }, /* 0x54 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EBP, FLG_NONE, OPC_PUSH }, /* 0x55 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ESI, FLG_NONE, OPC_PUSH }, /* 0x56 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EDI, FLG_NONE, OPC_PUSH }, /* 0x57 */

	{TBL_ONE_BYTE, MODE_DEFAULT,  FLG_REG_CONST | EAX, FLG_NONE, OPC_POP }, /* 0x58 */
	{TBL_ONE_BYTE, MODE_DEFAULT,  FLG_REG_CONST | ECX, FLG_NONE, OPC_POP }, /* 0x59 */
	{TBL_ONE_BYTE, MODE_DEFAULT,  FLG_REG_CONST | EDX, FLG_NONE, OPC_POP }, /* 0x5A */
	{TBL_ONE_BYTE, MODE_DEFAULT,  FLG_REG_CONST | EBX, FLG_NONE, OPC_POP }, /* 0x5B */
	{TBL_ONE_BYTE, MODE_DEFAULT,  FLG_REG_CONST | ESP, FLG_NONE, OPC_POP }, /* 0x5C */
	{TBL_ONE_BYTE, MODE_DEFAULT,  FLG_REG_CONST | EBP, FLG_NONE,  OPC_POP }, /* 0x5D */
	{TBL_ONE_BYTE, MODE_DEFAULT,  FLG_REG_CONST | ESI, FLG_NONE, OPC_POP }, /* 0x5E */
	{TBL_ONE_BYTE, MODE_DEFAULT,  FLG_REG_CONST | EDI, FLG_NONE,  OPC_POP }, /* 0x5F */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_PUSHA }, /* 0x60 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_POPA }, /* 0x61 */

    /* I'm sketchy on this one;
     the intel manuals didn't say the same thing as the reference I'm using.
     I went with the manual of course. */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_RM,  OPC_BOUND }, /* 0x62 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_REG,  OPC_ARPL }, /* 0x63 */

	{TBL_ONE_BYTE, MODE_INVALID, FLG_PREFIX, FLG_NONE,  FLG_NONE }, /* 0x64 */
	{TBL_ONE_BYTE, MODE_INVALID, FLG_PREFIX, FLG_NONE, FLG_NONE }, /* 0x65 */
	{TBL_ONE_BYTE, MODE_INVALID, FLG_PREFIX, FLG_NONE,  FLG_NONE }, /* 0x66 */
	{TBL_ONE_BYTE, MODE_INVALID, FLG_PREFIX, FLG_NONE, FLG_NONE }, /* 0x67 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_IMM, FLG_NONE, OPC_PUSH }, /* 0x68 */

    /** use table with 3 operands */
	{NOT_IMPLEMENTED}, /* 0x69 */

	{TBL_ONE_BYTE, MODE_8, FLG_IMM8, FLG_NONE, OPC_PUSH }, /* 0x6A */

	/** use table with 3 operands */
	{NOT_IMPLEMENTED}, /* 0x6B */

	{TBL_ONE_BYTE, MODE_8, FLG_NONE, FLG_NONE, OPC_INS }, /* 0x6C */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_INS }, /* 0x6D */
	{TBL_ONE_BYTE, MODE_8, FLG_NONE, FLG_NONE, OPC_OUTS }, /* 0x6E */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_OUTS }, /* 0x6F */


	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JO }, /* 0x70 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JNO }, /* 0x71 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JB }, /* 0x72 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JNB }, /* 0x73 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JE }, /* 0x74 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JNE }, /* 0x75 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JBE }, /* 0x76 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JNBE }, /* 0x77 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JS }, /* 0x78 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JNS }, /* 0x79 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JP }, /* 0x7A */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JNP }, /* 0x7B */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JL }, /* 0x7C */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JNL }, /* 0x7D */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JNE }, /* 0x7E */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JNLE }, /* 0x7F */

    /**
     * These four bytes all have an opcode extension - TODO */
	{TBL_ONE_BYTE_GRP, MODE_INVALID , FLG_NOT_IMPLEMENTED,FLG_NOT_IMPLEMENTED,FLG_NOT_IMPLEMENTED}, /* 0x80 */
	{TBL_ONE_BYTE_GRP, MODE_INVALID , FLG_NOT_IMPLEMENTED,FLG_NOT_IMPLEMENTED,FLG_NOT_IMPLEMENTED}, /* 0x81 */
	{TBL_ONE_BYTE_GRP, MODE_INVALID , FLG_NOT_IMPLEMENTED,FLG_NOT_IMPLEMENTED,FLG_NOT_IMPLEMENTED}, /* 0x82 */
	{TBL_ONE_BYTE_GRP, MODE_INVALID , FLG_NOT_IMPLEMENTED,FLG_NOT_IMPLEMENTED,FLG_NOT_IMPLEMENTED}, /* 0x83 */

	{TBL_ONE_BYTE, MODE_8, FLG_RM, FLG_REG | FLG_8BIT, OPC_TEST }, /* 0x84 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_REG, OPC_TEST }, /* 0x85 */

	{TBL_ONE_BYTE, MODE_8, FLG_REG, FLG_RM | FLG_8BIT, OPC_XCHG }, /* 0x86 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_RM, OPC_XCHG }, /* 0x87 */

	{TBL_ONE_BYTE, MODE_8, FLG_RM , FLG_REG | FLG_8BIT, OPC_MOV }, /* 0x88 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_REG, OPC_MOV }, /* 0x89 */
	{TBL_ONE_BYTE, MODE_8, FLG_REG, FLG_RM | FLG_8BIT, OPC_MOV }, /* 0x8A */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_RM, OPC_MOV }, /* 0x8B */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_MODRM_MEM | FLG_REG, FLG_SREG, OPC_MOV }, /* 0x8C */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG, FLG_MODRM_MEM | FLG_RM, OPC_LEA }, /* 0x8D */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_SREG, FLG_RM, OPC_MOV }, /* 0x8E */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_RM, FLG_NONE, OPC_POP }, /* 0x8F */

    /* xchg eax, eax == nop !*/
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_NOP }, /* 0x90 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ECX, FLG_REG_CONST | EAX, OPC_XCHG }, /* 0x91 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EDX, FLG_REG_CONST | EAX, OPC_XCHG }, /* 0x92 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EBX, FLG_REG_CONST | EAX, OPC_XCHG }, /* 0x93 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ESP, FLG_REG_CONST | EAX, OPC_XCHG }, /* 0x94 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EBP, FLG_REG_CONST | EAX, OPC_XCHG }, /* 0x95 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ESI, FLG_REG_CONST | EAX, OPC_XCHG }, /* 0x96 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EDI, FLG_REG_CONST | EAX, OPC_XCHG }, /* 0x97 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_CBW }, /* 0x98 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE,  OPC_CDQ }, /* 0x99 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_PTR16, FLG_NONE, OPC_CALL }, /* 0x9A */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_WAIT }, /* 0x9B */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_PUSHF }, /* 0x9C */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_POPF }, /* 0x9D */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_SAHF }, /* 0x9E */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_LAHF }, /* 0x9F */

	{NOT_IMPLEMENTED }, /* 0xA0 */
	{NOT_IMPLEMENTED }, /* 0xA1 */
	{NOT_IMPLEMENTED }, /* 0xA2 */
	{NOT_IMPLEMENTED }, /* 0xA3 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_MOVS }, /* 0xA4 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_MOVS }, /* 0xA5 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_CMPS }, /* 0xA6 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_CMPS }, /* 0xA7 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | FLG_8BIT | AL, FLG_IMM8, OPC_TEST }, /* 0xA8 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_IMM, OPC_TEST }, /* 0xA9 */

	{TBL_ONE_BYTE, MODE_8, FLG_NONE, FLG_NONE, OPC_STOS }, /* 0xAA */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_STOS }, /* 0xAB */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_CMPS }, /* 0xAC */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_CMPS }, /* 0xAD */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_CMPS }, /* 0xAE */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_CMPS }, /* 0xAF */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | FLG_8BIT | AL, FLG_IMM8, OPC_MOV }, /* 0xB0 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | FLG_8BIT | CL, FLG_IMM8, OPC_MOV }, /* 0xB1 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | FLG_8BIT | DL, FLG_IMM8, OPC_MOV }, /* 0xB2 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | FLG_8BIT | BL, FLG_IMM8, OPC_MOV }, /* 0xB3 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | FLG_8BIT | AH, FLG_IMM8, OPC_MOV }, /* 0xB4 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | FLG_8BIT | CH, FLG_IMM8, OPC_MOV }, /* 0xB5 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | FLG_8BIT | DH, FLG_IMM8,  OPC_MOV }, /* 0xB6 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | FLG_8BIT | BH, FLG_IMM8, OPC_MOV }, /* 0xB7 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_IMM, OPC_MOV }, /* 0xB8 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ECX, FLG_IMM, OPC_MOV }, /* 0xB9 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EDX, FLG_IMM, OPC_MOV }, /* 0xBA */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EBX, FLG_IMM, OPC_MOV }, /* 0xBB */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ESP, FLG_IMM, OPC_MOV }, /* 0xBC */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EBP, FLG_IMM,  OPC_MOV }, /* 0xBD */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | ESI, FLG_IMM, OPC_MOV }, /* 0xBE */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EDI, FLG_IMM, OPC_MOV }, /* 0xBF */

    /**
     * more opcodes with lame extensions
     */
	{TBL_ONE_BYTE_GRP, MODE_INVALID, FLG_NONE, FLG_NONE, FLG_NONE}, /* 0xC0 */
	{TBL_ONE_BYTE_GRP, MODE_INVALID, FLG_NONE, FLG_NONE, FLG_NONE}, /* 0xC1 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_IMM16, FLG_NONE, OPC_RETN }, /* 0xC2 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_RETN }, /* 0xC3 */

	/**
	 * lame opcodes that I don't know how to make work right now
	 */
	{NOT_IMPLEMENTED }, /* 0xC4 */
	{NOT_IMPLEMENTED }, /* 0xC5 */

	{TBL_ONE_BYTE_GRP, MODE_INVALID, FLG_NONE, FLG_NONE, FLG_NONE}, /* 0xC6 */
	{TBL_ONE_BYTE_GRP, MODE_INVALID, FLG_NONE, FLG_NONE, FLG_NONE}, /* 0xC7 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_IMM16, FLG_IMM8, OPC_ENTER }, /* 0xC8 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_LEAVE }, /* 0xC9 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_IMM16, FLG_NONE, OPC_RETF }, /* 0xCA */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_RETF }, /* 0xCB */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_INT3 }, /* 0xCC */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_INT }, /* 0xCD */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_INTO }, /* 0xCE */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_IRET }, /* 0xCF */

	/**
	 * moar opcode extension shit
	 */
	{TBL_ONE_BYTE_GRP, MODE_INVALID, FLG_NONE, FLG_NONE, FLG_NONE}, /* 0xD0 */
	{TBL_ONE_BYTE_GRP, MODE_INVALID, FLG_NONE, FLG_NONE, FLG_NONE}, /* 0xD1 */
	{TBL_ONE_BYTE_GRP, MODE_INVALID, FLG_NONE, FLG_NONE, FLG_NONE}, /* 0xD2 */
	{TBL_ONE_BYTE_GRP, MODE_INVALID, FLG_NONE, FLG_NONE, FLG_NONE}, /* 0xD3 */

	/**
	 * these two have secondary opcodes
	 */
	{NOT_IMPLEMENTED }, /* 0xD4 */
	{NOT_IMPLEMENTED }, /* 0xD5 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_SALC }, /* 0xD6 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_XLAT }, /* 0xD7 */

	/**
	 * The x86 architecture is a fckin nightmare.
	 * These opcodes have an extension AND a secondary
	 * opcode.
	 */
	{NOT_IMPLEMENTED }, /* 0xD8 */
	{NOT_IMPLEMENTED }, /* 0xD9 */
	{NOT_IMPLEMENTED }, /* 0xDA */
	{NOT_IMPLEMENTED }, /* 0xDB */
	{NOT_IMPLEMENTED }, /* 0xDC */
	{NOT_IMPLEMENTED }, /* 0xDD */
	{NOT_IMPLEMENTED }, /* 0xDE */
	{NOT_IMPLEMENTED }, /* 0xDF */

	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_LOOPNZ }, /* 0xE0 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_LOOPZ }, /* 0xE1 */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_LOOP }, /* 0xE2 */

	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JECXZ }, /* 0xE3 */

	{TBL_ONE_BYTE, MODE_8, FLG_REG_CONST  | AL, FLG_IMM8, OPC_IN }, /* 0xE4 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REG_CONST | EAX, FLG_IMM,  OPC_IN }, /* 0xE5 */

	{TBL_ONE_BYTE, MODE_8, FLG_IMM8, FLG_REG_CONST | FLG_8BIT | AL, OPC_OUT }, /* 0xE6 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_IMM, FLG_REG_CONST | EAX, OPC_OUT }, /* 0xE7 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REL, FLG_NONE, OPC_CALL }, /* 0xE8 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_REL, FLG_NONE, OPC_JMP }, /* 0xE9 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_PTR16, FLG_NONE, OPC_JMPF }, /* 0xEA */
	{TBL_ONE_BYTE, MODE_8, FLG_REL8, FLG_NONE, OPC_JMP }, /* 0xEB */

	{NOT_IMPLEMENTED }, /* 0xEC */
	{NOT_IMPLEMENTED }, /* 0xED */
	{NOT_IMPLEMENTED }, /* 0xEE */
	{NOT_IMPLEMENTED }, /* 0xEF */

	{TBL_ONE_BYTE, MODE_INVALID, FLG_PREFIX, FLG_NONE, FLG_NONE }, /* 0xF0 */

	{NOT_IMPLEMENTED }, /* 0xF1 */

	{TBL_ONE_BYTE, MODE_INVALID, FLG_PREFIX, FLG_NONE, FLG_NONE }, /* 0xF2 */
	{TBL_ONE_BYTE, MODE_INVALID, FLG_PREFIX, FLG_NONE, FLG_NONE }, /* 0xF3 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_HLT }, /* 0xF4 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_CMC }, /* 0xF5 */

	{TBL_ONE_BYTE_GRP, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE }, /* 0xF6 */
	{TBL_ONE_BYTE_GRP, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE }, /* 0xF7 */

	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_CLC }, /* 0xF8 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_STC }, /* 0xF9 */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_CLI }, /* 0xFA */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_STI }, /* 0xFB */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_CLD }, /* 0xFC */
	{TBL_ONE_BYTE, MODE_DEFAULT, FLG_NONE, FLG_NONE, OPC_STD }, /* 0xFD */

	{TBL_ONE_BYTE_GRP, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE }, /* 0xFE */
	{TBL_ONE_BYTE_GRP, FLG_NONE, FLG_NONE, FLG_NONE, FLG_NONE}, /* 0xFF */

};
